sudo: false
language: c
dist: trusty
env:
  global:
addons:
  apt:
    packages:
    - docbook
    - docbook-dsssl
    - docbook-xsl
    - libbsd-dev
    - libedit-dev
    - libosp5
    - libostyle1c2
    - libpam0g-dev
    - libperl-dev
    - libpython3.4
    - libxml2-utils
    - openjade
    - opensp
    - python3
    - python3-dev
    - python3-minimal
    - tcl8.5
    - tcl8.5-dev
    - xsltproc
script:
  - ./configure
  - make docs
  - if git diff $TRVIS_BRANCH|grep "^+.* $" ; then echo "余分な空白があります" && false; fi
  - make -C doc/src/sgml check
  - make -C src/bin/psql sql_help.h
deploy:
  provider: pages
  repo: github.com/noborus/noborus.github.io/current
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  kepp_history: true
  target_branch: master
  local_dir: doc/src/sgml/html
  on:
    branch: travis-deploy
