sudo: false
language: c
dist: trusty
env:
  global:
addons:
  apt:
    packages:
    - docbook
    - docbook-dsssl
    - docbook-xsl
    - libbsd-dev
    - libedit-dev
    - libosp5
    - libostyle1c2
    - libpam0g-dev
    - libperl-dev
    - libpython3.4
    - libxml2-utils
    - openjade
    - opensp
    - python3
    - python3-dev
    - python3-minimal
    - tcl8.5
    - tcl8.5-dev
    - xsltproc
script:
  - ./configure
  - make docs
  - make -C src/bin/psql sql_help.h
